using System;

namespace TradingBotAPI.CoreBot.Models
{
    /// <summary>
    /// Represents a trade signal generated by a strategy
    /// and stored in the SQLite database.
    /// </summary>
    public class Trade
    {
        public int Id { get; set; }              // Primary key (auto-increment)
        public string Symbol { get; set; }       // e.g., "BTC/USD"
        public decimal Price { get; set; }       // Trade price
        public decimal Quantity { get; set; }    // Quantity traded
        public DateTime Timestamp { get; set; }  // UTC timestamp

        // Strategy metadata
        public TradeAction Action { get; set; }  // Buy / Sell / Hold (enum now!)
        public string Strategy { get; set; }     // Strategy name (e.g., "RSI", "MACrossover")
    }
}
